### PR TITLE
Look up CallSets by sample ID

### PR DESCRIPTION
**Pull request by adamnovak**
Allowing search by sample ID, and reworking some comments.

### CODE REVIEW

**Comment by adamnovak** [comment]
OK, I have brought this up to speed with master and pared it down to just the `CallSet` change: you can now look up `CallSet`s by sample ID.

**Comment by pgrosu** [comment]
Nice!  Thank you for this @adamnovak :)

**Comment by jeromekelleher** [comment]
Can you give a quick example of the use case please @adamnovak ? How does this interact semantically with the other fields in the request? Should this be unioned with null so it can be omitted?

**Comment by adamnovak** [comment]
The use case is to look up CallSets by sample ID; if you went over to the metadata API and found a sample you care about, you will need to be able to get genotype information for it.

I meant to have semantics where an empty array doesn't apply the filter; I forgot to specify that in the comment and will fix that momentarily.

**Comment by adamnovak** [comment]
OK, it now describes the proper syntax for not using this field.

**Comment by adamnovak** [comment]
Sorry, now it *actually* actually describes the proper syntax for not using the field; I had amended my commit without adding the file.

**Comment by jeromekelleher** [comment]
Thanks @adamnovak, +1.

**Comment by david4096** [comment]
@adamnovak can we close given https://github.com/ga4gh/schemas/pull/636?

**Pull request closed without merging**
