### PR TITLE
Beacon

### PR DESCRIPTION
**Pull request by maximilianh**
This is another suggestion for a beacon API. It replaces most fields with three key-value maps.

### CODE REVIEW

**Comment by diekhans** [comment]
Suggest have the values in key-value maps as arrays of strings.
This removes the need to come up with magic syntax that then has
to be parsed for both complex values and multi-valued
attributes.

**Comment by mbaudis** [comment]
@maximilianh @mcupak Can we remove this in favour of current Beacon development?

**Comment by mcupak** [comment]
I don't think I have the permissions needed to close this, but whoever does, please do so. This is out of date.

**Comment by mbaudis** [comment]
Closed in favour of current Beacon development efforts.

**Pull request closed without merging**
