### PR TITLE
Adding developers section

### PR DESCRIPTION
**Pull request by heuermh**
Progress towards #278.

The [requirements for sync to Maven Central](http://central.sonatype.org/pages/requirements.html#developer-information) requires a ```<developers>``` section.  This pull request uses the list of github user names at https://github.com/ga4gh/schemas/graphs/contributors sorted alphabetically.

Other options may be names as reported by ```git shortlog```
```bash
$ git shortlog -s
    21  Adam Novak
     1  Alexander W Blocker
    41  Angel Pizarro
...
```

names and email addresses as reported by ```git log```
```bash
$ git log | grep Author: | sort | uniq
Author: Adam Novak <anovak@...>
Author: Alexander W Blocker <ablocker@...>
Author: Angel Pizarro <angel@...>
Author: Angel Pizarro <delagoya@...>
...
```

or a generic project developer
```xml
<developer>
  <name>GA4GH developers</name>
</developer>
```

If developers would like to add additional metadata (e.g. ```<name>```, ```<email>```,```<organization>```, etc. to this pull request, please do so.

### CODE REVIEW

**Comment by fnothaft** [comment]
Might be preferable for brevity to just list @richarddurbin and @haussler who are GA4GH Data Working Group chairs.

**Comment by heuermh** [comment]
Good suggestion, @fnothaft.  I made this a separate pull request to allow for discussion.

**Comment by delagoya** [comment]
@heuermh which PR are you referring to WRT @fnothaft's point? I'm not seeing it.

**Comment by heuermh** [comment]
@delagoya sorry, I meant that this pull request is separate from #279 because I expected there to be more discussion on this one.

**Comment by delagoya** [comment]
OK. @fnothaft suggested replacement of full developer list (since this changes often) with just @haussler and @richarddurbin 

Are there implications for Maven Central if we do not list the full set of developers? E.g. only David or Richard can push the artifacts to Maven Central (which is not what we want)

**Comment by heuermh** [comment]
The ```<developers>``` section in the pom is informational only.  Some projects (e.g. Apache) like to include all developers and contributors, other projects find it not worth the trouble and just use a generic developer like above.

I don't have any strong opinions on this, so I'd be fine with closing this in favor of another pull request that did something else.

**Comment by delagoya** [comment]
@heuermh in that case I would vote to just list the project leads. Can you change your PR to just include @haussler and @richarddurbin, then we can +1 for merge?

**Comment by heuermh** [comment]
Closing this issue in favor of #288 per discussion above.

**Pull request closed without merging**
