### PR TITLE
Fail CI if avro-tools issues warnings

### PR DESCRIPTION
**Pull request by dcolligan**
- change metadata time types from string to union { null, string } to
    eliminate warnings
- also remove compile_schemas verbosity flag, plus some other
    refactoring

Issue #306

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Great work @dcolligan, +1.

**Comment by macieksmuga** [comment]
+1, thanks @dcolligan!

**Comment by mbaudis** [comment]
-1
This has been a design decision in https://github.com/ga4gh/schemas/pull/301. I would rather support keeping it that way; basic requirements for any record should be (uu)id, creation time, update time, no matter what it is about (one could argue about update if considering an object immutable).

**Comment by dcolligan** [comment]
@mbaudis the warning I'm fixing here stems from having an attribute set to a default value which is impossible for that attribute's type to accommodate.  Alternatively, an empty string could be the default.  Would you be satisfied with that?

**Comment by macieksmuga** [comment]
@mbaudis @dcolligan the other alternative - potentially closer to the spirit of #301 - is to leave the definition as a string, but not to provide any default value (the user is then required to supply an explicit value in all cases).

**Comment by mbaudis** [comment]
>  a default value which is impossible for that attribute's type to accommodate
 So it should be just

```string recordCreateTime;```

... right? Sorry for this. Agree & change?

**Comment by dcolligan** [comment]
@mbaudis sounds good to me.  Just pushed a change to that effect.

**Comment by macieksmuga** [comment]
@dcolligan @mbaudis thanks for working through this - it was blocking me as well.

**Comment by macieksmuga** [comment]
+1 for the updated fix.

**Comment by mbaudis** [comment]
+1 now, and retraction of my -1 above.
However, I feel not comfortable enough to merge it in myself due to the test suite changes in this commit - could somebody else do this, please?

**Comment by jeromekelleher** [comment]
Looks like we have agreement; merging.

**Pull request merged**
