### PR TITLE
add an introduction to variant objects

### PR DESCRIPTION
**Pull request by dglazer**
@diekhans -- a small PR for the documentation branch

This PR includes a reference to an image -- I don't know how to easily add that image in the right way, so I'm just including it here -- it should be moved to _static/variant_objects.png.

variant_objects

### CODE REVIEW

**Comment by diekhans** [comment]
We need images source in a vector format.  I would suggest
Inkscape, as it's cross-platform, powerful, free, and it's
source format is SVG, which can be displayed natively.

**Comment by mbaudis** [comment]
Now SVG can't be posted inline here ... Sorry for the longish & not very object like (translate ...) code.

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xl="http://www.w3.org/1999/xlink" version="1.1"
	width="660"
	height="375"
	xmlns:dc="http://purl.org/dc/elements/1.1/">
<defs>
  <style type="text/css">
   <![CDATA[
    text {
        font-family: "Helvetica";
        font-size: 12;
    }
    rect {
    	fill:		none;
    	stroke-linecap:		"round";
    	stroke-linejoin:	"round";
    	stroke-width:			3px;
    	stroke-dasharray: 10,10;
    }
    line {
    	stroke:	rgb(163,163,163);
    	stroke-opacity:	0.5;
    	stroke-linecap:		"round";
    	stroke-linejoin:	"round";
    	stroke-width:			3px;
		}
    .dark {
    	stroke-opacity:	1;    
    }
   ]]>
 </style>
</defs>

<rect x="20" y="20"  rx="20" ry="20" stroke="green" width="400" height="350" />
<rect x="25" y="175"  rx="10" ry="10" stroke="red" width="390" height="40" />
<rect x="125" y="25"  rx="10" ry="10" stroke="blue" width="40" height="340" />
<rect x="275" y="275"  rx="10" ry="10" stroke="orange" width="40" height="40" />

<line x1="70" y1="25" x2="70" y2="365" class="dark"/>
<line x1="120" y1="25" x2="120" y2="365"/>
<line x1="170" y1="25" x2="170" y2="365"/>
<line x1="220" y1="25" x2="220" y2="365"/>
<line x1="270" y1="25" x2="270" y2="365"/>
<line x1="320" y1="25" x2="320" y2="365"/>
<line x1="370" y1="25" x2="370" y2="365"/>

<line x1="25" y1="70" x2="415" y2="70" class="dark" />
<line x1="25" y1="120" x2="415" y2="120" />
<line x1="25" y1="170" x2="415" y2="170" />
<line x1="25" y1="220" x2="415" y2="220" />
<line x1="25" y1="270" x2="415" y2="270" />
<line x1="25" y1="320" x2="415" y2="320" />

<text x="80" y="60" font-weight="900">CS1</text>
<text x="130" y="60" font-weight="900">CS2</text>
<text x="180" y="60" font-weight="900">CS3</text>
<text x="230" y="60" font-weight="900">CS4</text>
<text x="280" y="60" font-weight="900">CS5</text>
<text x="330" y="60" font-weight="900">...</text>

<text x="40" y="105" font-weight="900">V1</text>
<text x="40" y="155" font-weight="900">V2</text>
<text x="40" y="205" font-weight="900">V3</text>
<text x="40" y="255" font-weight="900">V4</text>
<text x="40" y="305" font-weight="900">V5</text>
<text x="40" y="355" font-weight="900">...</text>

<text x="140" y="105" font-weight="900">C</text>
<text x="190" y="105" font-weight="900">C</text>
<text x="140" y="155" font-weight="900">C</text>
<text x="240" y="155" font-weight="900">C</text>
<text x="290" y="155" font-weight="900">C</text>
<text x="90" y="205" font-weight="900">C</text>
<text x="190" y="255" font-weight="900">C</text>
<text x="240" y="255" font-weight="900">C</text>
<text x="290" y="305" font-weight="900">C</text>

<rect x="440" y="55"  rx="20" ry="20" stroke="green" width="200" height="110" />
<text x="500" y="120" font-weight="900">VariantSet</text>
<rect x="440" y="175"  rx="20" ry="20" stroke="red" width="200" height="40" />
<text x="510" y="200" font-weight="900">Variant</text>
<rect x="440" y="225"  rx="20" ry="20" stroke="blue" width="200" height="40" />
<text x="510" y="250" font-weight="900">CallSet</text>
<rect x="440" y="275"  rx="20" ry="20" stroke="orange" width="200" height="40" />
<text x="520" y="300" font-weight="900">Call</text>

</svg>
```

**Comment by dglazer** [comment]
@diekhans -- all the current documentation images (in https://github.com/ga4gh/schemas/tree/documentation/doc/source/_static) are .png files , which is why I picked that format. I just don't think GitHub lets me upload new binary files from the web UI, and I didn't want to fuss with setting up a Git client and using the cmdline. (Esp. since my primary machine is a chromebook.)

@mbaudis -- thanks for that conversion -- I added it to my branch, and it looks great when I click on it. 

@diekhans -- unfortunately, GitHub doesn't seem to display the .svg file inline in the doc -- no idea if it will work in the final documentation.

So -- if someone can add the .png to the branch, I think we're good.
Or -- if someone can get .svg to work in GitHub, I think we're good.

**Comment by mbaudis** [comment]
> @mbaudis <https://github.com/mbaudis> -- thanks for that conversion -- I added it to my branch, and it looks great when I click on it. 
> 
> 
Good. Let’s just say it was a bit of CDO* on my part.

*OCD, ordered alphabetically

**Comment by diekhans** [comment]
@mbaudis the SVG is editable with inkscape and probably other
SVG editors.

@dglazer the goal of SVG is to have the source so it can be
edited.  We can either have the PNG created manually whenever
anyone changes the image or automatically by the doc build
process.

thanks!!

**Comment by jeromekelleher** [comment]
I think this is a good start on making the current API more explicit. 

+1.

(Minor nitpick process-wise @dglazer: would it be possible to make PRs from a fork rather than a branch on the main repo? We have rather a lot of branches now (22; I'm not sure what the majority of these are for), and having people editing the main repo for routine stuff substantially increases the risk of bad things happening.)

**Comment by dglazer** [comment]
@jeromekelleher -- happy to use a fork next time.

@diekhans -- testing our process -- I think you can merge this any time you're happy with it, and I can then delete the branch -- is that right?

**Comment by diekhans** [comment]
thanks @dglazer

**Pull request merged**
