### PR TITLE
Baseline - latest core references/reads/variants schemas

### PR DESCRIPTION
**Pull request by macieksmuga**
The intention of this PR is to bring all three GA4GH projects, `schemas`, `server` and `compliance` in synch with each other by first adopting a common baseline, then re-adding the teams' contributions one-by-one to all three repositories simultaneously.

### CODE REVIEW

**Comment by macieksmuga** [comment]
I can squash the individual commits that went into creating baseline, but I left them separate for now if somebody wants to examine how each individual team's code was separated (one team's contributions per commit).

I left `Experiment` and `Dataset` within the `metadata` module, as these are used in the baseline `reads`.  I also left `common` alone for now, with the idea that its constituent records could be refactored into other modules in another PR.

**Comment by diekhans** [comment]
+1

**Comment by skeenan** [comment]
+1

**Comment by dglazer** [comment]
+1.

The comment on Dataset is now pretty out of date, but we can fix that separately. I wrote up suggested language to describe the original intent in https://github.com/ga4gh/schemas/pull/319#issuecomment-109291693 if you'd prefer to include it now.

**Comment by jeromekelleher** [comment]
+1.

**Comment by lh3** [comment]
+1

**Comment by skeenan** [comment]
This has all the +1s we need. Merging.

**Pull request merged**
