### PR TITLE
Add filters_applied, filters_passed, and filters_failed to variant

### PR DESCRIPTION
**Pull request by heuermh**
See https://github.com/ga4gh/schemas/pull/656#issuecomment-272273999

### CODE REVIEW

**Comment by david4096** [comment]
Thank you kindly! We try to avoid renumbering tags or reusing tags. It's not important that the tag numbers are in order, but if a field hasn't changed it's tag number shouldn't change either. This helps guarantee that clients at future versions of the protocol can still handle messages, and field names can be reused safely.

**Comment by heuermh** [comment]
Got it, I'll fix and rebase

**Comment by heuermh** [comment]
Addressed review comments and squashed commits.

**Comment by david4096** [comment]
This PR is awaiting implementation.

**Comment by heuermh** [comment]
Sorry, what do you mean by implementation?

Note that if any code implementation relies on htsjdk, it will run into unresolved issue:
Genotype requires a method filtersWereApplied (https://github.com/samtools/htsjdk/issues/741)

Let me know if I should rebase and force push to address the necessary merge.

**Comment by david4096** [comment]
Hi @heuermh! We look forward to merging this one but need to include it in our existing implementation before we can move forward. Leaving that comment as a reminder to the group that we should implement this sooner, rather than later. That implementation relies on pysam https://github.com/ga4gh/server/issues/1539 .

**Comment by heuermh** [comment]
I see, thanks!

**Comment by david4096** [comment]
Closed in favor of https://github.com/ga4gh/schemas/pull/827

**Comment by heuermh** [comment]
Thanks!

**Pull request closed without merging**
