### PR TITLE
Update metadata.avdl

### PR DESCRIPTION
**Pull request by mbaudis**
Changing to ```Biosample``` from ```Sample```, as per discussion https://github.com/ga4gh/schemas/pull/391 and metadata call from 2015-08-27.

### CODE REVIEW

**Comment by eleanorstanley** [comment]
+1
(presuming my vote counts! Biosample is more consistently used within academia hence my vote)

**Comment by nmulder** [comment]
I agree with change to Biosample

**Comment by lh3** [comment]
+1

**Comment by mbaudis** [comment]
Biosample it is; merging. Thanks!

**Pull request merged**
