### PR TITLE
Update rna_quantifications.rst

### PR DESCRIPTION
**Pull request by ksens**
Link to `schemas` page was broken

### CODE REVIEW

**Comment by kozbo** [comment]
Thanks for catching that @ksens! I took a look at your PR and it just needs a minor change. The path should be `../schemas/rna_quantification.proto.html` instead of `../schemas/rnaquantification.html`
With that change I will give my +1 :-)

**Comment by ksens** [comment]
Done. Please check.

**Comment by kozbo** [comment]
sorry, still missing the underbar :-) one more try?

**Comment by ksens** [comment]
Done. Please check. Hopefully I got it right this time :)

**Comment by kozbo** [comment]
Yes, thanks @ksens!

**Pull request merged**
