### PR TITLE
Adding quality, filtersFailed, and filtersPassed to Variant, fixes #219

### LINKED ISSUE #219: GAVariant missing "quality" and "filter"
Hi,  the v0.5.1 GAVariant specification does not list the "filter" and "quality" fields,  which are part of the VCF specification.   However, variants I fetch from https://www.googleapis.com/genomics/v1beta2/variants/search do include them.   Is this a mistake in the specification,  or are these fields no longer required?

### PR DESCRIPTION
**Pull request by heuermh**
Using changes proposed by @johntbates in pull request #220 and @fnothaft in comment
https://github.com/ga4gh/schemas/pull/220#issuecomment-91592681

### CODE REVIEW

**Comment by adamnovak** [comment]
Do we want our filters to just be strings, or do we want some complicated ontology of filter types and their parameters?

**Comment by heuermh** [comment]
Sorry for the noise, rebased and squashed second commit to fix non-ascii doc characters.

**Comment by kozbo** [comment]
Please see #656 to close this

**Comment by david4096** [comment]
Closing in favor of #656

**Pull request closed without merging**
