### PR TITLE
Simplify list reference bases endpoint

### PR DESCRIPTION
**Pull request by david4096**
The GA4GH genomics API offers a utility for listing the bases of a given reference, by ID. However, the access pattern for getting these bases differs from the remainder of the API. This PR suggests that the API could be made more consistent by enabling the familiar RPC style message passing as opposed to the query string.

For example, when listing variants via the variants API, a search variants request is sent to the variants RPC endpoint. This same problem might have been alternatively solved using the URL string `/variants?start=0&end=123123&referenceName=1`, where the fields of the search variants request would be populated via the query string. Although both approaches are valid, the former is favored throughout the schemas.

This PR does nothing to modify the functionality of the API, it simply changes a GET request to a POST request to improve the consistency of our offering by unifying access patterns.

### CODE REVIEW

**Comment by diekhans** [comment]
+1  in should be consistend

While this isn't intended to be traditional `RPC' (it's still
stateless) , post are used due to the difficulty in encoding
complex requests as a flat query string.

There was discussion of providing for both options; simple
requests could use GET, while more complex ones would require
POST of JSON.  There maybe a ticket, but nothing ever came of
this discussion.

**Comment by david4096** [comment]
@jeromekelleher What do you think of this? It's the only endpoint that uses query parameters and would be trivial to change to a POST.

**Comment by diekhans** [comment]
Can anyone for the reads task team comment on the rationale for this inconsistency and then vote.

**Comment by kozbo** [comment]
+1  @cassiedoll do you have any objections to this change?

**Comment by fnothaft** [comment]
IIRC, @delagoya is the person to comment RE reads task team.

**Comment by jeromekelleher** [comment]
I don't think this change helps much, as the request is still an outlier. Why do we have the ID in the URL  instead of the request? Why is it called ListReferenceBases instead of SearchReferenceBases? Making the API consistent is a good goal, but this change doesn't really help that much.

**Comment by delagoya** [comment]
Have to agree with @jeromekelleher here. If you are shifting to using a JSON packet for a POST request, then the URL should change to not have URL parameters at all.

**Comment by david4096** [comment]
Thanks @delagoya and @jeromekelleher! It sounds like there is consensus for a new endpoint that accepts `ListReferenceBasesRequest`. I've unceremoniously named it `/listreferencebases`.

**Comment by kozbo** [comment]
+1 update looks like it meets the most recent requests

**Comment by kozbo** [comment]
bump. Would like to get this completed as it is blocking our ability to add the schema annotations required for going from protobuf to swagger.

**Comment by delagoya** [comment]
+1 looks good to me. 

Sorry for the delay!

**Comment by delagoya** [comment]
@kozbo would you like me to merge?

**Comment by kozbo** [comment]
@delagoya Yes please, thanks!

**Comment by dcolligan** [comment]
Looks like there's consensus... merging...

**Pull request merged**
