### PR TITLE
Remove 'make' from maven build. Use sphinx-maven

### PR DESCRIPTION
**Pull request by david4096**
This solves a build problem currently affecting compliance/master.

A recent change reinstated the `mvn package` functionality of generating documentation. This was done by using the `exec` plugin to run `make docs`, which in turn runs the python toolchain.

Unfortunately, this approach doesn't work in environments where the python dependency tree isn't being managed. This caused errors when packaging the schemas on jitpack, which we use for developing the compliance tests.

This PR allows maven to generate docs as part of the `mvn package` phase and adds the `sphinx_rtd_theme` to guarantee the schemas will build in the jitpack environment.

```
cd doc/source && sphinx-build -b html -d ../../target/doc/doctrees . ../../target/doc/html
/bin/bash: sphinx-build: command not found
make: *** [docs] Error 127
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.705 s
[INFO] Finished at: 2016-07-12T22:26:18+00:00
[INFO] Final Memory: 25M/450M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (build-docs) on project ga4gh-schemas: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
```

When run against the PR this branch originates from the build is successful as seen [here](https://jitpack.io/com/github/ga4gh/schemas/fd34a2f/build.log). @diekhans

### CODE REVIEW

**Comment by diekhans** [comment]
+1, this makes much more sense than running make to run sphinx.

**Comment by kozbo** [comment]
+1

**Comment by kozbo** [comment]
Ran the 'mvn package' command without any errors. I did get a bunch of warnings during the GA4GH JSON serialization:
'''
/Users/kosborn/Documents/dev/kevin-ga4gh-schemas/doc/source/schemas/reads.proto.rst:None: WARNING: protobuf:message reference target not found: string
/Users/kosborn/Documents/dev/kevin-ga4gh-schemas/doc/source/schemas/reads.proto.rst:None: WARNING: protobuf:message reference target not found: integer
/Users/kosborn/Documents/dev/kevin-ga4gh-schemas/doc/source/schemas/reads.proto.rst:None: WARNING: protobuf:message reference target not found: long
'''
along with some errors mentioning indentation.
'''
/Users/kosborn/Documents/dev/kevin-ga4gh-schemas/doc/source/schemas/struct.proto.rst:18: ERROR: Unexpected indentation.
'''
I am not sure what else to do to test this build, though I can say that it no longer fails the mvn command.

**Comment by david4096** [comment]
@kozbo I believe you'll find the same warnings in the doc generation process ran via `make docs`, right now and that they don't present anything new.

**Pull request merged**
