### PR TITLE
document the current behavior of the Dataset object

### PR DESCRIPTION
**Pull request by dglazer**
*This PR replaces #325, which got confused during the master branch cleanup -- content is the same.*

This comment-only PR is in response to @jeromekelleher 's request (in #248) for clearer documentation of the original intent of the Dataset object, and to the discussion (in #319) that led to moving it to metadata.avdl (thanks @mbaudis).

My main goal here is to capture the current behavior in a formal visible way, as a baseline for discussion of any changes. I'd like to merge this in as is, and then discuss any changes to behavior or fields in a separate PR.

### CODE REVIEW

**Comment by dglazer** [comment]
@skeenan @diekhans @jeromekelleher @mbaudis -- I think this is non-controversial -- if so, can we get some +1's? (And if not, let's discuss.)

**Comment by mbaudis** [comment]
+1 for the description, sure!

Next up: the general definition of id types and how to use them for references ...

**Comment by diekhans** [comment]
+1 nice example of details descriptions.

**Comment by skeenan** [comment]
Ok merging.

**Pull request merged**
