### PR TITLE
Biodata

### PR DESCRIPTION
**Pull request by david4096**
Add link to individual in biodata schema documentation. Change `createTime` to `createDateTime` and `updateTime` to `updateDateTime`.

@diekhans @mbaudis I would like to open up a PR against master soon, would be great to have the biodata protocol reviewed and edited before it is opened to the group.

### CODE REVIEW

**Comment by david4096** [comment]
Note: I've added the `datasetId` field to both `Individual` and `BioSample`.

**Comment by mbaudis** [comment]
@david4096 This is problematic. IMO datasets should reference the included biosampleIds. Each Individual / Biosample will potentially be part of n^x Dataset's.

**Comment by david4096** [comment]
@mbaudis Ok, no problem it's removed from the record so implementors are free to have biosamples/individuals across datasets. Note that when searching for biosample or individual records one must specify a datasetId.

**Comment by diekhans** [comment]
maybe making the names of the create/update field consistent with reads is the way to go for now.  Adding  *DataTime  didn't really improve the clarity of what these fields really mean (create of data vs load into server).

**Comment by diekhans** [comment]
This all looks great for a first pass.  Lets get it in and use it.

**Comment by mbaudis** [comment]
+1

**Pull request merged**
