### PR TITLE
Validation of the schema by Eagle, comments/questions added

### PR DESCRIPTION
**Pull request by eleanorstanley**
For discussion by the members of the metadata task team :)

### CODE REVIEW

**Comment by diekhans** [comment]
This is fantastic @eleanorstanley   Would you mind making this a pull request against the metadata branch of schemas?

**Comment by eleanorstanley** [comment]
Oh what a wally, apologies. Rereading emails I was asked to edit the branch but as I have only edited "master" before I was unfamiliar with what this meant - I know now! I have made all the changes to branch ready to do a new PR.
What I dont know how to do is delete this unwanted PR ... what I can do is close the issue which I will do now!

**Comment by dcolligan** [comment]
You have successfully closed this PR, but you will need to make a new topic branch (with identical changes as this PR) in your local repo and then use that branch as the basis for a new PR against the ga4gh:metadata branch.  (I believe GitHub does not allow more than one PR open per topic branch.)

**Comment by dcolligan** [comment]
(There is no concept in GitHub of "deleting" PRs.  You can always delete branches, but the PRs and all the comments on them stick around.)

**Comment by eleanorstanley** [comment]
Thank you for your advice, I believe I have now submitted a PR to the
metadata branch, I hope so :)
Ele

*Eleanor Stanley* MSc(Res)
Biocurator and Information security manager

*Eagle Genomics Ltd*
T: +44 (0)1223 497377
http://www.eaglegenomics.com
Disclaimer: http://www.eaglegenomics.com/about/privacy-statement/

*eagle*core Best in Show Finalist at Bio-IT World 2015, web-based services
and software

**Pull request closed without merging**
