### PR TITLE
Updated beacon to 0.2

### PR DESCRIPTION
**Pull request by hershman**
This PR is a WIP that translates the [beacon 0.2 spec](https://docs.google.com/document/d/154GBOixuZxpoPykGKcPOyrYUcgEXVe2NvKx61P4Ybn4/edit#) into avro.  The beacon 0.2 spec is still under discussion so this PR is a little premature, but I needed this avro file for a beacon PR I'm working on for the Server.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Thanks for this @hershman, it's great to see this update to the Beacon API in Avro form. 

As a more general question, I wonder if it would be possible for the Beacon API design process to happen here on GitHub? The structure of the new Beacon API here is quite different to the reads/variants API, and it would be great if we could keep these reasonably consistent with each other.

**Comment by skeenan** [comment]
+1 @hershman 

@jeromekelleher @mfiume Beacon team have agreed that the Beacon development will move here

**Comment by maximilianh** [comment]
+1

**Comment by jeromekelleher** [comment]
Thanks @skeenan, that's great news!

+1 to merging the PR.

**Comment by mfiume** [comment]
+1 thanks @hershman!

**Comment by bartgrantham** [comment]
+1 Great work, Steve!

**Comment by jeromekelleher** [comment]
This is ready to merge; @hershman, could you squash the commits down please?

**Comment by hershman** [comment]
The commits are squashed.

**Comment by jeromekelleher** [comment]
Merged; thanks @hershman!

**Pull request merged**
