### PR TITLE
Variation annotation - update docs to remove impact

### PR DESCRIPTION
**Pull request by sarahhunt**
The schema and documentation are currently out of sync. This fixes the text; an update to the diagram is also required.

### CODE REVIEW

**Comment by david4096** [comment]
+1

**Comment by andrewjesaitis** [comment]
PR #566 against variation_annotation updates the diagram. Thanks for the heads up Sarah!

**Comment by reece** [comment]
rst files needed updating. See PR #567.

**Comment by reece** [comment]
I added the variant_annotation branch to read the docs. See here:
https://ga4gh-schemas.readthedocs.org/en/variation_annotation/

@diekhans CallSet and Variant create and update were not switched to ISO 8601 and the concurrent DateTime naming. Intentional?

**Comment by reece** [comment]
Verified that impact doesn't appear in docs:
https://ga4gh-schemas.readthedocs.org/en/variation_annotation/search.html?q=impact&check_keywords=yes&area=default

**Comment by reece** [comment]
@sarahhunt @diekhans @david4096 @andrewjesaitis @jeromekelleher @fcunningham Would one of you please review this PR soon? Since I screwed up the last one, I'd like to get this right before merging. :disappointed: 

Reminder: This PR is only about updating the docs that were out-of-sync when I merged 3 days ago. You only to to ensuring that you don't see any stale docs w.r.t. the removal of impact.

Updated docs based on the current v_a branch are here:
https://ga4gh-schemas.readthedocs.org/en/variation_annotation/

**Comment by reece** [comment]
+1

**Comment by jeromekelleher** [comment]
+1

The 'removing impact' bit looks good. The changes wrt to update times and so on are getting confusing though, and I'm not sure it's a good idea just make them on just this 'corner' of the API. We should make a decision about what we're going to do with them and apply it API wide.

**Comment by reece** [comment]
@jeromekelleher: I went with your +1 since this is a clear improvement over the current state, and I added #568 so that we can decide on a consistent time format.

**Comment by jeromekelleher** [comment]
@reece --- sorry for the vague comment, merging followed by discussion of the time formats was what I intended.

**Pull request merged**
