### PR TITLE
Sphinx domain for Avro

### PR DESCRIPTION
**Pull request by peterolph**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
A quick scan says this looks really cool! Any pointers to some example output, or docs for usage?

**Comment by diekhans** [comment]
Nice.
We  already have an avro Sphix domain in the documentation branch.   How dose this compare with what is in that branch?  It would me good to merge this into the documentation branch.

**Comment by diekhans** [comment]
@peterolph GA4GH is have a docathon on Nov 7th to flesh out the sphinx doc.   Would be create to contrast this to what we have and work with you to come up with a good system

**Comment by diekhans** [comment]
this code is already incorporated in the documentation branch.  Please make suggested changes there

**Comment by peterolph** [comment]
@diekhans aha thanks. I didn't see that my code had already been merged on another branch.

**Pull request closed without merging**
