### PR TITLE
Adding a script to make GraphViz UMLs

### PR DESCRIPTION
**Pull request by adamnovak**
This script can be run thusly:

```
$ contrib/make_uml.sh
```

It will produce a UML diagram with edges in doc/uml.png and
doc/uml.dot.

To make room for these, I am renaming the existing UML Dia file and its SVG.

An example of the UML you get can be seen here:

http://hgwdev.sdsc.edu/~anovak/images/autouml.png

### CODE REVIEW

**Comment by diekhans** [comment]
Awesome..  GraphViz rocks.

One request, create PDF instead of PNG.  That way it scales when zoomed
and you can copy and paste from it.

**Comment by adamnovak** [comment]
I'm actually having dot make an SVG. I just put the PNG up for people to
see.

**Comment by diekhans** [comment]
Perfect!  I can see SVG :-)

**Comment by benedictpaten** [comment]
+1 Wow Adam, that's an impressively documented script!

**Comment by skeenan** [comment]
+1

**Comment by delagoya** [comment]
+1

Nice work!

**Comment by david4096** [comment]
Closing with https://github.com/ga4gh/schemas/pull/756. Thanks @adamnovak and @malisas !

**Pull request closed without merging**
