### PR TITLE
Retired Task Team process documentation change

### PR DESCRIPTION
**Pull request by delagoya**
I added a section to explicitly define the issue resolution process for retired task teams.

### CODE REVIEW

**Comment by skeenan** [comment]
+1

**Comment by jeromekelleher** [comment]
+1.

**Comment by delagoya** [comment]
Anyone want to merge later today? @fnothaft ?

**Comment by skeenan** [comment]
Bueller?

**Comment by pgrosu** [comment]
@skeenan :)

**Comment by fnothaft** [comment]
Merged! Thanks @delagoya!

**Comment by skeenan** [comment]
Thanks @fnothaft

**Pull request merged**
