### PR TITLE
Fix metadata.avdl dateOfBirth format

### PR DESCRIPTION
**Pull request by mbaudis**
Fixed the ```dateOfBirth``` attribute to now ISO8601.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This seems sensible @mbaudis. There's a couple of things that are iffy about this from a git perspective though:

1. I think we should be making pull requests from personal forks for this sort of minor change, and not creating branches within the central schemas repo. There's quite a few stale branches lying around now that need clean up I think.
2. There seems to be some extra commits in here.

**Comment by mbaudis** [comment]
@jeromekelleher Not sure about the first point; isn't it better to do it this way, to avoid stale / conflicting branches? I'm not the only one doing it like that (lame excuse, and I'm habby for procedural advice).

Re 2.: I don't understand them showing up, since IMHO I did fork this off master. But there is another oddity (for me); https://github.com/ga4gh/schemas/pull/319 was merged after lengthy arguments and back-and-forth commits, but the changes have disappeared from master.

Do we have somebody with the job to clean up/help out with Github problems?

**Comment by jeromekelleher** [comment]
@mbaudis --- no, I think we should avoid writing directly to the central repo unless absolutely necessary, as having lots of people making un-audited changes to the central repo will lead to a major mess. Which has (given your disappearing changes) probably happened already. I don't think there's anyone responsible for maintaining the git repo.

The CONTRIBUTING.md file is clear on the recommended process: create a fork, and make a PR from this fork. I think the second issue will probably resolve itself if you close this PR, create a fork, and make a PR from this.

**Comment by fnothaft** [comment]
I am +1 to @jeromekelleher's suggested approach (fork and pull request).

**Comment by mbaudis** [comment]
There is now a "metadata" branch for consistent handling of metadata.avdl & related modifications.

**Comment by pgrosu** [comment]
Thanks @mbaudis :)

**Pull request closed without merging**
