### PR TITLE
Incorporate documentation sprint into master

### PR DESCRIPTION
**Pull request by reece**

### CODE REVIEW

**Comment by dglazer** [comment]
+1 -- this documentation is a big step forward, and while it's not perfect, having it all in master will avoid drift and will make it easy to make incremental improvements. Thank you @reece .

_Note to reviewers: you can ignore the diffs in `doc/src/schemas/*.rst`, since those are all auto-generated from .avdl files. We hope to get rid of the need to check them in at all when we switch to proto._

**Comment by jeromekelleher** [comment]
Is there a link to the current output? It would be nice to have a quick look before voting.

**Comment by reece** [comment]
@jeromekelleher I should have noted that in the PR. Yes, built here: http://ga4gh-schemas.readthedocs.org/en/documentation/.

0cbc2e8c in the docs footer is the commit hash of the documentation branch head at https://github.com/ga4gh/schemas/tree/documentation.

**Comment by jeromekelleher** [comment]
Wow, this is awesome!

+1e6

**Comment by diekhans** [comment]
+1 this is fantatstic

**Comment by macieksmuga** [comment]
+1 - great work all. FYI, I'm happy to merge this topic branch as is - squishing it down to a single commit may require something like this: 

http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit

and I'm not sure that's necessary here - but please chime in if you want to see a squish like this happen.

**Comment by reece** [comment]
This looks like +4.

@diekhans, I think we're waiting to hear whether you feel strongly about squishing or not. If not, we merge immediately. If so, I think Maciej volunteered to be the squisher.

**Comment by diekhans** [comment]
Yea, Maciej, go head a squish!

**Comment by jeromekelleher** [comment]
I don't think squashing is appropriate here --- we'd lose the contributions from a whole bunch of different people. The history is a little messy, but that's the nature of doc updates.

I say we merge as-is.

**Comment by macieksmuga** [comment]
Went with the no squish route after talking it over further with Mark. Lots and lots of thanks again to all the people involved in the documentation sprint!

**Comment by reece** [comment]
On Wed, Nov 25, 2015 at 12:11 PM, Maciek Smuga-Otto <
notifications@github.com> wrote:

> Went with the no squish route after talking it over further with Mark.
> Lots and lots of thanks again to all the people involved in the
> documentation sprint!


Yippee! Great to have this in!  Thanks everyone!

**Comment by dglazer** [comment]
Awesome! Thank you everyone. Looks like the documentation branch is ready to retire -- who wants to do the honors?

**Comment by reece** [comment]
On Fri, Nov 27, 2015 at 5:34 AM, David Glazer <notifications@github.com>
wrote:

> Awesome! Thank you everyone. Looks like the documentation branch is ready
> to retire -- who wants to do the honors?


There are five outstanding PRs against the documentation branch that we
should resolve before closing:
https://github.com/ga4gh/schemas/pulls?q=is%3Aopen+label%3ADocumentation+is%3Apr

Anyone know the status of these?



   - <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
   Update documentation branch  <https://github.com/ga4gh/schemas/pull/456>
   <https://github.com/ga4gh/schemas/pull/456#partial-pull-merging>
    Documentation
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
   #456 opened 21 days ago by wbrockman
   <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Awbrockman>

    18 <https://github.com/ga4gh/schemas/pull/456>
   +1
   - <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
   Draft release notes for version 0.6.
   <https://github.com/ga4gh/schemas/pull/449>
   <https://github.com/ga4gh/schemas/pull/449#partial-pull-merging>
    Documentation
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
   #449 opened 24 days ago by hjellinek
   <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Ahjellinek>

    9 <https://github.com/ga4gh/schemas/pull/449>
   +1
   - <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
   Initial commit of RNA API design documentation
   <https://github.com/ga4gh/schemas/pull/435>
   <https://github.com/ga4gh/schemas/pull/435#partial-pull-merging>
    Documentation
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
   #435 opened on Oct 7 by saupchurch
   <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Asaupchurch>

    0 <https://github.com/ga4gh/schemas/pull/435>
   +1
   - <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
   First draft of a streaming protocol specification for the GA4GH API
   <https://github.com/ga4gh/schemas/pull/431>
   <https://github.com/ga4gh/schemas/pull/431#partial-pull-merging>
    Documentation
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
   #431 opened on Sep 30 by diekhans
   <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Adiekhans>

    22 <https://github.com/ga4gh/schemas/pull/431>
   +1
   - <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
   Added descriptions of error conditions
   <https://github.com/ga4gh/schemas/pull/422>
   <https://github.com/ga4gh/schemas/pull/422#partial-pull-merging>
    Documentation
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
   #422 opened on Sep 22 by hjellinek
   <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Ahjellinek>

    9 <https://github.com/ga4gh/schemas/pull/422>
   +1

**Comment by diekhans** [comment]
documentation branch removed

**Comment by diekhans** [comment]
Opps, I deleted too soon.

However, documentation label doesn't mean documentation branch.

There are RNA one was just for review

   - <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
   Update documentation branch  <https://github.com/ga4gh/schemas/pull/456>
   <https://github.com/ga4gh/schemas/pull/456#partial-pull-merging>
    Documentation
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
   #456 opened 21 days ago by wbrockman
   <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Awbrockman>

    18 <https://github.com/ga4gh/schemas/pull/456>
   +1
   - <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
   Draft release notes for version 0.6.
   <https://github.com/ga4gh/schemas/pull/449>
   <https://github.com/ga4gh/schemas/pull/449#partial-pull-merging>
    Documentation
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
   #449 opened 24 days ago by hjellinek
   <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Ahjellinek>

    9 <https://github.com/ga4gh/schemas/pull/449>
   +1
   - <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
   Initial commit of RNA API design documentation
   <https://github.com/ga4gh/schemas/pull/435>
   <https://github.com/ga4gh/schemas/pull/435#partial-pull-merging>
    Documentation
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
   #435 opened on Oct 7 by saupchurch
   <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Asaupchurch>

    0 <https://github.com/ga4gh/schemas/pull/435>
   +1
   - <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
   First draft of a streaming protocol specification for the GA4GH API
   <https://github.com/ga4gh/schemas/pull/431>
   <https://github.com/ga4gh/schemas/pull/431#partial-pull-merging>
    Documentation
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
   #431 opened on Sep 30 by diekhans
   <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Adiekhans>

    22 <https://github.com/ga4gh/schemas/pull/431>
   +1
   - <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
   Added descriptions of error conditions
   <https://github.com/ga4gh/schemas/pull/422>
   <https://github.com/ga4gh/schemas/pull/422#partial-pull-merging>
    Documentation
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
   <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
   #422 opened on Sep 22 by hjellinek
   <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Ahjellinek>

    9 <https://github.com/ga4gh/schemas/pull/422>
   +1


---
Reply to this email directly or view it on GitHub:
https://github.com/ga4gh/schemas/pull/504#issuecomment-160175016

----------------------------------------------------------------------
On Fri, Nov 27, 2015 at 5:34 AM, David Glazer <notifications@github.com>
wrote:

> Awesome! Thank you everyone. Looks like the documentation branch is ready
> to retire -- who wants to do the honors?


There are five outstanding PRs against the documentation branch that we
should resolve before closing:
https://github.com/ga4gh/schemas/pulls?q=
is%3Aopen+label%3ADocumentation+is%3Apr

Anyone know the status of these?



- <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
    Update documentation branch <https://github.com/ga4gh/schemas/pull/456>
    <https://github.com/ga4gh/schemas/pull/456#partial-pull-merging>
    Documentation
    <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    #456 opened 21 days ago by wbrockman
    <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Awbrockman>
    18 <https://github.com/ga4gh/schemas/pull/456>
    +1
    ** this is the is it ReST discussion; there was never any resolution as to `why' it isn't ReST.
    
- <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
    Draft release notes for version 0.6.
    <https://github.com/ga4gh/schemas/pull/449>
    <https://github.com/ga4gh/schemas/pull/449#partial-pull-merging>
    Documentation
    <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
    <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
    #449 opened 24 days ago by hjellinek
    <https://github.com/ga4gh/schemas/issues?q=
    is%3Apr+is%3Aopen+author%3Ahjellinek>
    9 <https://github.com/ga4gh/schemas/pull/449>
    +1
    *** this is not against documentation branch
    

- <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
    Initial commit of RNA API design documentation
    <https://github.com/ga4gh/schemas/pull/435>
    <https://github.com/ga4gh/schemas/pull/435#partial-pull-merging>
    Documentation
    <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
    <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
    #435 opened on Oct 7 by saupchurch
    <https://github.com/ga4gh/schemas/issues?q=
    is%3Apr+is%3Aopen+author%3Asaupchurch>
    0 <https://github.com/ga4gh/schemas/pull/435>
    +1
    ** PR is only for review
    
- <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
    First draft of a streaming protocol specification for the GA4GH API
    <https://github.com/ga4gh/schemas/pull/431>
    <https://github.com/ga4gh/schemas/pull/431#partial-pull-merging>
    Documentation
    <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
    <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
    #431 opened on Sep 30 by diekhans
    <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen+author%3Adiekhans>
    22 <https://github.com/ga4gh/schemas/pull/431>
    +1
    *** PR only for review, not against documentation branch
    
- <https://github.com/ga4gh/schemas/issues?q=is%3Apr+is%3Aopen>
    Added descriptions of error conditions
    <https://github.com/ga4gh/schemas/pull/422>
    <https://github.com/ga4gh/schemas/pull/422#partial-pull-merging>
    Documentation
    <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3ADocumentation>
    in progress
    <https://github.com/ga4gh/schemas/issues?q=is%3Aopen+label%3A%22in+progress%22>
    #422 opened on Sep 22 by hjellinek
    <https://github.com/ga4gh/schemas/issues?q=
    is%3Apr+is%3Aopen+author%3Ahjellinek>

    9 <https://github.com/ga4gh/schemas/pull/422>
    +1
    *** this we should merge into master.

**Comment by diekhans** [comment]
Actually, I don't think
https://github.com/ga4gh/schemas/pull/422 is ready to merge
either.  Issues with HTTP codes that need resolved.

We should create tickets to continue working on this (although there
might be some already)

**Pull request merged**
