### PR TITLE
Validation of the schema by Eagle, comments/questions added

### PR DESCRIPTION
**Pull request by eleanorstanley**
Second attempt - comments now made to the metadata branch (I hope!)
I don't believe I am able to add the label 'MetadataTaskTeam' - could someone add this please?
Thanks
Ele

### CODE REVIEW

**Comment by dcolligan** [comment]
The PR looks good, but the CI is failing.  If you want to merge this in at some point, the CI needs to be passing.  (Unless the people working on the metadata branch have stipulated otherwise... if you were merging into master, the CI would definitely need to be passing.)

**Comment by eleanorstanley** [comment]
The PR is mainly discussion items that need to be decided by the chairs of
the task team ... it should be an agenda item at the next TC and I will
leave it in their capable hands!
I have followed protocol dictated to me (once I did commit to the branch of
course!)
Ele

*Eleanor Stanley* MSc(Res)
Biocurator and Information security manager

*Eagle Genomics Ltd*
T: +44 (0)1223 497377
http://www.eaglegenomics.com
Disclaimer: http://www.eaglegenomics.com/about/privacy-statement/

*eagle*core Best in Show Finalist at Bio-IT World 2015, web-based services
and software

**Comment by mbaudis** [comment]
@eleanorstanley Thanks for the comments! Very helpful - I'll try if to work on them ASAP. One note: if encountering obvious typos, you can just correct them - much less overhead. Introduced one yourself, though (line 160...). Also, pls. try to wrap at 80; otherwise the GitGods may complain ...

@dcolligan Right; seems at first scroll to be an aberrant comment wrap.

**Comment by eleanorstanley** [comment]
Good evening,

Apologies but I wasn't sure of the etiquette!
Happy to correct typos. Apologies for making my own but it was more work
than I anticipated merging with the branch, it was very different to
master, so I was a bit rushed.
I also didn't know about line wrapping, I will remember if I make a PR
again. Though with all the shenanigans of this one you may not want me to!

Regards
Eleanor

**Comment by dcolligan** [comment]
@eleanorstanley There's no need for another PR; your topic branch is correctly targeting the metadata branch.  You can push more commits to your branch (or force push a new commit) and the PR will update automatically.

**Comment by mbaudis** [comment]
@eleanorstanley 

```
 /**
  The age of the individual (not of the sample) at time of sample collection.
  This field may be approximate.
  Format: ISO 8601 duration PnYnMnDTnHnMnS in a suitable approximation
  Example: P12Y3M
  [TODO: Eagle: This feels like a mix of concepts, ageAtSampling is a distinct time
  point but ISO 8601 duration is to capture a time interval. If this is for
  the ageAtSampling then a unit needs to be captured and this should be
  explicit in the example. If this really is to reflect a time interval then
  additional context information is required to defined the TimeDate from
  which the interval/duration is defined.]
  Age at sampling should have units and is required as we may be missing DOB.
  */
```
No, any age is not a time point, but a duration (birth => observation).

**Comment by diekhans** [comment]
@eleanorstanley, Helen and myself did a pass of ending, including updating the documentation to hopeful answer some of your questions.  There are still some in there and we added a lot more TODO items.  Please see what we did and continue the process.  We feel that if you or anyone has to ask a question, the documentation isn't good enough. This is really, really helpful.  Thank you

**Comment by eleanorstanley** [comment]
@diekhans Could you please point me to the updated documentation? I have cruised areas I can see in github (https://github.com/ga4gh/metadata-team/wiki, https://github.com/ga4gh/schemas) and the Google drive folder for metadata task team and cannot identify any updated documents to read. Thanks

**Comment by diekhans** [comment]
@eleanorstanley, documentation changes are the avdl in  the metadata branch of the schemas:
   https://github.com/ga4gh/schemas/blob/metadata/src/main/resources/avro/metadata.avdl
   https://github.com/ga4gh/schemas/blob/metadata/src/main/resources/avro/ontologies.avdl

**Comment by eleanorstanley** [comment]
@diekhans Thank you for the clarification, I misinterpreted your use of the word "documentation". The schemas are looking good, evolving rapidly. I am tempted to validate with a slightly different clinical dataset, but feel I should let the new updates settle first for others to view/contribute to.

**Pull request merged**
