### PR TITLE
Add protocol.py

### PR DESCRIPTION
**Pull request by dcolligan**
Issue https://github.com/BD2KGenomics/ga4gh-integration/issues/53

### CODE REVIEW

**Comment by david4096** [comment]
This removes redundant code and will make the schemas python module much easier to use.

**Comment by dcolligan** [comment]
@david4096 ready for review

**Comment by dcolligan** [comment]
Actually, hold on... there's a few problems.

https://travis-ci.org/ga4gh/server/builds/199079898

I need to add the `encodeValue` and `setAttribute` methods and fix `getValueFromValue`

**Comment by dcolligan** [comment]
@david4096 ok, should be good now

**Comment by david4096** [comment]
CI is failing and I'm not able to replicate locally. It seems like it might be a CI bug working off a different commit? Gonna try closing and reopening.

**Pull request merged**
